name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK

      uses: google-github-actions/setup-gcloud@main 
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      env:
        DOCKER_CLI_ASK_PASS: "0"

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/your-image-name:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/your-image-name:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy your-service-name \
          --image ${{ secrets.DOCKER_USERNAME }}/your-image-name:${{ github.sha }} \
          --platform managed \
          --region your-region \
          --allow-unauthenticated
